spring:
  application:
    name: eventticket

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/event_ticket_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:mySecretKeyMySecretKeyMySecretKey123456NeedToBeAtLeast32BytesLong}
  expiration: 86400000

vnpay:
  tmnCode: ${VNPAY_TMN_CODE:QAM9V9WJ}
  hashSecret: ${VNPAY_HASH_SECRET:2WJP5Q16YSWL39AS8LM35TZQ696WO4C2}
  payUrl: ${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  returnUrl: ${VNPAY_RETURN_URL:http://localhost:3000/}